import test from'node:test';import assert from'node:assert/strict';import{fork}from'node:child_process';import{readFile}from'node:fs/promises';
import{directEvidence,retirementMatches,requestRetirement,CloudRuntimeChannel,EVIDENCE_CHECK,RUNTIME_PROTOCOL}from'../scripts/notifications-cloud-runtime.mjs';
import{lifecycleObserver,childProcessIds,stopRuntimeChild}from'../scripts/notifications-runtime-process.mjs';
const uuid='aabbccdd-1234-4567-8901-abcdefabcdef',revision='9'.repeat(40),orch='8'.repeat(40);
const env={NOTIFICATIONS_WORKER_INSTANCE_ID:'gha-7-1',GITHUB_RUN_ID:'7',RELEASE_SHA:revision,SELF_HANDOFF_ORCHESTRATOR_SHA:orch};
const probe={healthy:true,live:200,ready:200,diagnostics:{leaseOwner:`gha-7-1:${uuid}`,leaseEpoch:2,workerRevision:revision,compatibility:'compatible',connectionPollSuccessCount:12,whatsAppPollErrorCount:0,consecutivePollErrors:0,queuePollSuccessCount:9,queuePollErrorCount:0,consecutiveQueuePollErrors:0,lastSuccessfulConnectionPoll:new Date().toISOString(),lastQueuePoll:new Date().toISOString(),errorCodeCounts:{P2032:0,P2021:0,P2022:0},outboundEnabled:false,authSecret:'must-not-export',phone:'+201234567890'}};
const evidence=()=>directEvidence({probe,env,wrapperPid:100,workerPids:[101]});
const request=()=>({protocol:RUNTIME_PROTOCOL,action:'retire',requestId:'12345678-1234-1234-1234-123456789abc',targetEvidenceCheckId:10,targetRunId:'7',targetOwner:probe.diagnostics.leaseOwner,targetEpoch:2,targetProcessUuid:uuid,revision,orchestrationSha:orch,createdAt:new Date(Date.now()-100).toISOString(),expiresAt:new Date(Date.now()+60000).toISOString()});
const check=value=>({id:10,name:EVIDENCE_CHECK,head_sha:orch,status:'in_progress',app:{slug:'github-actions'},output:{summary:JSON.stringify(value)}});
test('direct evidence is HTTP-derived and exports only allowlisted counters/identity',()=>{const v=evidence();assert.equal(v.liveHttpStatus,200);assert.equal(v.readyHttpStatus,200);assert.equal(v.processUuid,uuid);assert.equal(v.connectionPollSuccessCount,12);assert.doesNotMatch(JSON.stringify(v),/authSecret|must-not-export|201234567890/)});
test('different owner/revision/malformed counters fail evidence binding',()=>{for(const patch of [{leaseOwner:'wrong'},{workerRevision:orch},{queuePollErrorCount:'0'}])assert.throws(()=>directEvidence({probe:{...probe,diagnostics:{...probe.diagnostics,...patch}},env,wrapperPid:100,workerPids:[101]}))});
test('owner epoch UUID revision request expiry all bind retirement',()=>{assert.equal(retirementMatches(request(),evidence()),true);for(const patch of [{targetOwner:'wrong'},{targetEpoch:3},{targetProcessUuid:'wrong'},{revision:orch},{expiresAt:new Date(Date.now()-1).toISOString()},{createdAt:'bad'}])assert.equal(retirementMatches({...request(),...patch},evidence()),false)});
test('stale or malformed direct health refuses retire before creating any command',async()=>{for(const patch of [{observedAt:'bad'},{observedAt:new Date(Date.now()-61000).toISOString()},{healthy:false},{outboundEnabled:true},{epoch:3}]){let calls=0;const github={repository:'synthetic/test',request:async()=>{calls++;return check({...evidence(),...patch})}};await assert.rejects(requestRetirement({github,targetCheckId:10,expectedOwner:probe.diagnostics.leaseOwner,expectedEpoch:2,expectedRevision:revision,expectedOrchestration:orch}),/Retirement refused/);assert.equal(calls,1)}});
test('retire wait requires actual successful bound process acknowledgment',async()=>{let calls=0;const github={repository:'synthetic/test',request:async(path,options)=>{calls++;if(calls===1)return check(evidence());if(calls===2)return{id:20};return{status:'completed',conclusion:'success',output:{summary:JSON.stringify({...options?.body,requestId:'wrong',acknowledgment:{}})}}}};await assert.rejects(requestRetirement({github,targetCheckId:10,expectedOwner:probe.diagnostics.leaseOwner,expectedEpoch:2,expectedRevision:revision,expectedOrchestration:orch}),/acknowledgment binding invalid/)});
test('checks permission failure prevents channel initialization',async()=>{const channel=new CloudRuntimeChannel({github:{repository:'synthetic/test',request:async()=>{throw Error('HTTP 403')}},env});await assert.rejects(channel.initialize(),/403/);assert.equal(channel.evidenceId,null)});
test('forced or incomplete shutdown cannot publish success acknowledgment',async()=>{let body;const channel=new CloudRuntimeChannel({github:{repository:'synthetic/test',request:async(_,options)=>{body=options.body}},env});channel.evidenceId=10;channel.evidence=evidence();const value=await channel.finish({exitCode:0,forced:false,noOrphans:true,workerStoppingObserved:true,heartbeatStoppedObserved:false,wrapperWorkerExitCode:0});assert.equal(value.success,false);assert.equal(body.conclusion,'failure')});
async function runtime(ms=30){const child=fork(new URL('./fixtures/runtime-wrapper.mjs',import.meta.url),[],{env:{...process.env,TEST_WORKER_STOP_MS:String(ms)},stdio:['ignore','pipe','pipe','ipc']});const lifecycle=lifecycleObserver(child,{tee:false});await new Promise((resolve,reject)=>{child.once('error',reject);let output='';child.stdout.on('data',chunk=>{output+=chunk;if(output.includes('test.nested_ready'))setTimeout(resolve,80)})});return{child,lifecycle,pids:childProcessIds(child.pid)}}
test('E slow nested shutdown waits before acknowledgment, no orphan',async()=>{const{child,lifecycle,pids}=await runtime(250);const start=Date.now();const ack=await stopRuntimeChild(child,{reason:'slow',gracefulTimeoutMs:2000,lifecycle,workerPids:pids});assert.ok(Date.now()-start>=240);assert.equal(ack.exitCode,0);assert.equal(ack.noOrphans,true);assert.equal(ack.heartbeatStoppedObserved,true);assert.equal(ack.wrapperWorkerExitCode,0)});
test('F already-exited child has truthful state without sending another signal',async()=>{const{child,lifecycle,pids}=await runtime();const done=new Promise(resolve=>child.once('exit',resolve));child.kill('SIGTERM');await done;const ack=await stopRuntimeChild(child,{reason:'already-exited',gracefulTimeoutMs:100,lifecycle,workerPids:pids});assert.equal(ack.alreadyExited,true);assert.equal(ack.signalForwarded,null);assert.equal(ack.exitCode,0);assert.equal(ack.noOrphans,true)});
test('E deadline failure is reported forced and never acknowledged as graceful',async()=>{const{child,lifecycle,pids}=await runtime(600);try{const ack=await stopRuntimeChild(child,{reason:'deadline',gracefulTimeoutMs:40,lifecycle,workerPids:pids});assert.equal(ack.forced,true);assert.notEqual(ack.exitCode,0)}finally{for(const pid of pids)try{process.kill(pid,'SIGKILL')}catch{}}});
test('production launch uses exec and bounded existing lease gate, never raw node shell child',async()=>{const y=await readFile(new URL('../.github/workflows/notifications-worker-self-handoff.yml',import.meta.url),'utf8');assert.match(y,/run: exec node scripts\/notifications-self-handoff.mjs session/);assert.match(y,/checks: write/);assert.match(y,/SELF_HANDOFF_RUNTIME_EXPORT_ENABLED: "true"/)});

test('retirement TTL uses one clock instant even if the clock advances between fields',async t=>{let clock=Date.now()+1000;t.mock.method(Date,'now',()=>clock++);let calls=0,command;const github={repository:'synthetic/test',request:async(_,options)=>{calls++;if(calls===1)return check(evidence());if(calls===2){command=JSON.parse(options.body.output.summary);return{id:20}}return{status:'completed',conclusion:'success',output:{summary:JSON.stringify({...command,acknowledgment:{owner:probe.diagnostics.leaseOwner,epoch:2,processUuid:uuid,shutdown:{exitCode:0,forced:false,noOrphans:true}}})}}}};await requestRetirement({github,targetCheckId:10,expectedOwner:probe.diagnostics.leaseOwner,expectedEpoch:2,expectedRevision:revision,expectedOrchestration:orch});assert.equal(Date.parse(command.expiresAt)-Date.parse(command.createdAt),300000);assert.equal(retirementMatches(command,evidence(),Date.parse(command.createdAt)+1),true)});
